package:
  name: smesh # lower case name of package, may contain '-' but no spaces
  version: 6.5.3.1_netgen_5.3.1 # version of package. Should use the PEP-386 verlib

source:
  git_url: https://github.com/tpaviot/smesh.git
  git_tag: review/netgen-5.3.1

build:
  # The build number should be incremented for new builds of the same version
  number: 0     # (defaults to 0)
  binary_relocation: true # (defaults to true)

requirements:
  build:
    - gcc # gfortran
    - opencascade_community_edition >=0.16.0,<0.17.0

#  # Packages required to run the package. These are the dependencies that
#  # will be installed automatically whenever the package is installed.
  run:
    - opencascade_community_edition >=0.16.0,<0.17.0

about:
  home: https://github.com/tpaviot/smesh
  summary: finite element generation for oce (opencascade community edition)
  license: LGPL
