package:
  name: smesh # lower case name of package, may contain '-' but no spaces
  version: 6.5.3.1 # version of package. Should use the PEP-386 verlib

source:
  git_url: https://github.com/tpaviot/smesh.git
  git_tag: master

build:
  # The build number should be incremented for new builds of the same version
  number: 2     # (defaults to 0)
  binary_relocation: true # (defaults to true)

requirements:
  build:
    - gcc # gfortran
    - cmake
    - opencascade_community_edition 0.16.1

#  # Packages required to run the package. These are the dependencies that
#  # will be installed automatically whenever the package is installed.
  run:
    - opencascade_community_edition 0.16.1

about:
  home: https://github.com/tpaviot/smesh
  summary: finite element generation for oce (opencascade community edition)
  license: LGPL
